import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: [

  ],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
      <link
        rel="shortcut icon"
        href="/icon.png"
        type="image/png"
        sizes="32x32"
      />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
